<?php get_header(); ?>

<!-- Основной контейнер -->
<div class="vbox wb_container" id="wb_main">

    <div class="vbox wb_container" id="wb_main">

        <div class="wb_cont_inner"><div id="wb_element_instance51" class="wb_element wb-menu"><ul class="hmenu"><li class="active"><a href="zernoochistka/" target="_self">Зерноочистительное оборудование</a><ul><li><a href="predvaritelnaya_ochistka/" target="_self">Предварительная очистка</a><ul><li><a href="MPO50/" target="_self">МПО-50</a></li><li><a href="MZK-70/" target="_self">МЗК-70</a></li></ul></li><li><a href="pervichnaya_ochistka/" target="_self">Первичная очистка</a><ul><li><a href="ZVS/" target="_self">ЗВС-20</a></li><li><a href="OVS/" target="_self">ОВС-25</a></li><li><a href="VRM/" target="_self">ВРМ-К 52.7</a></li><li><a href="ZSK-70/" target="_self">ЗСК-70</a></li></ul></li><li><a href="vtorichnaya_ochistka/" target="_self">Вторичная очистка</a><ul><li><a href="trier/" target="_self">Триерный блок АЗТБ</a></li></ul></li></ul></li><li><a href="transport/" target="_self">Транспорт</a><ul><li><a href="norii/" target="_self">Нории</a></li><li><a href="transporter_tsc/" target="_self">Транспортер горизонтальный ТСЦ</a></li><li><a href="zernometateli/" target="_self">Зернометатели</a></li></ul></li><li><a href="zernosyshilki/" target="_self">Зерносушилки</a><ul><li><a href="ventum_syshilka/" target="_self">Шахтные сушилки Ventum</a></li><li><a href="zernosyshilki_atm/" target="_self">Мобильные зерносушилки АТМ</a></li></ul></li><li><a href="ZAV/" target="_self">Зерновые комплексы</a></li><li><a href="opriskivateli/" target="_self">Опрыскиватели</a></li></ul><div class="clearfix"></div></div><div id="wb_element_instance53" class="wb_element"><a class="wb_button" href="pervichnaya_ochistka/"><span>Первичная очистка</span></a></div><div id="wb_element_instance54" class="wb_element"><a class="wb_button" href="vtorichnaya_ochistka/"><span>Вторичная очистка</span></a></div><div id="wb_element_instance55" class="wb_element"><a class="wb_button" href="predvaritelnaya_ochistka/"><span>Предварительная очистка</span></a></div><div id="wb_element_instance56" class="wb_element wb_text_element" style=" line-height: normal;"><h2 class="wb-stl-heading2"><strong>Зерноочистительное оборудование</strong></h2></div><div id="wb_element_instance57" class="wb_element wb_element_picture" title=""><a href="MPO50/"><img alt="gallery/mpo-50" src="gallery_gen/e6a0698084ee344a43314babb8d2c629_200x200.jpg"></a></div><div id="wb_element_instance58" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">    На нашем производстве еженедельно изготавливается несколько десятков единиц зерноочистительной техники для выполнения различных задач, применяемой как в крупных автономных комплексах и предприятиях, так и в небольших крестьянских фермерских хозяйствах. У нас вы найдете: оборудование для предварительной, а также первичной и вторичной очистки зернового материала. Подробнее с модельным рядом и характеристиками вы можете ознакомиться ниже.</p>
            </div><div id="wb_element_instance59" class="wb_element wb_element_picture" title=""><img alt="gallery/овска" src="gallery_gen/6be3087caaf6fff6b8f0b235129539a8_200x174.jpg"></div><div id="wb_element_instance60" class="wb_element wb_element_picture" title=""><a href="OVS/"><img alt="gallery/овска" src="gallery_gen/6be3087caaf6fff6b8f0b235129539a8_200x174.jpg"></a></div><div id="wb_element_instance61" class="wb_element wb_element_picture" title=""><a href="ZVS/"><img alt="gallery/звс_2" src="gallery_gen/830ca7e745910e80f728a41f6d04b4ba_201x175.jpg"></a></div><div id="wb_element_instance62" class="wb_element wb_element_picture" title=""><a href="VRM/"><img alt="gallery/врм_к__2" src="gallery_gen/f93737500e9f3eb9567cc6362a70499f_201x171.jpg"></a></div><div id="wb_element_instance63" class="wb_element wb_element_picture" title=""><a href="trier/"><img alt="gallery/dsc_0126" src="gallery_gen/933319f7b4c4d08e7e3f18ded92f6769_202x170.jpg"></a></div><div id="wb_element_instance64" class="wb_element"><a class="wb_button" href="MPO50/"><span>МПО-50</span></a></div><div id="wb_element_instance65" class="wb_element"><a class="wb_button" href="OVS/"><span>ОВС-25</span></a></div><div id="wb_element_instance66" class="wb_element"><a class="wb_button" href="ZVS/"><span>ЗВС-20А</span></a></div><div id="wb_element_instance67" class="wb_element"><a class="wb_button" href="VRM/"><span>ВРМ-К52.7</span></a></div><div id="wb_element_instance68" class="wb_element"><a class="wb_button" href="trier/"><span>Триерный блок АЗТБ</span></a></div><div id="wb_element_instance69" class="wb_element wb_element_picture" title=""><a href="MZK-70/"><img alt="gallery/dsc0973" src="gallery_gen/578ac20c2eb51c16388368e02eae9a51_233x170.jpg"></a></div><div id="wb_element_instance70" class="wb_element"><a class="wb_button" href="MZK-70/"><span>МЗК-70</span></a></div><div id="wb_element_instance71" class="wb_element wb_element_picture" title=""><a href="ZSK-70/"><img alt="gallery/p_20180511_140401" src="gallery_gen/5424cd4a0cbe4bdd365752c9355068a0_233x180.jpg"></a></div><div id="wb_element_instance72" class="wb_element"><a class="wb_button" href="ZSK-70/"><span>ЗСК-70</span></a></div><div id="wb_element_instance73" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Предназначена для очистки колосовых, бобовых и др. сельхозкультур...</p>
            </div><div id="wb_element_instance74" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Очиститель вороха самопередвижной служит для подготовки продукции колосовых, бобовых, крупяных культур к закладке на длительное...</p>
            </div><div id="wb_element_instance75" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Машина первичной очистки зерна предназначена  для обработки сельхоз культур после уборки, выделения легких и тяжелых примесей...</p>
            </div><div id="wb_element_instance76" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Предназначена  для обработки крупяных, зерновых, бобовых культур, выделения крупных, мелких, зерновых и минеральных, легких...</p>
            </div><div id="wb_element_instance77" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Предназначен для выделения из зерновой массы длинных (овсюг, солома) и коротких (куколь, дробленка и т.д.) примесей...</p>
            </div><div id="wb_element_instance78" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Мобильный зерноочистительный комплекс. Высокая производительность, выгодная цена. Надежный за счет простоты конструкции...</p>
            </div><div id="wb_element_instance79" class="wb_element wb_text_element" style=" line-height: normal;"><p class="wb-stl-normal" style="text-align: justify;">Новый зерноочистительный самоходный комплекс. За очистительный процесс отвечает ВРМ-70, за погрузку и выгрузку...</p>
            </div><div id="wb_element_instance80" class="wb_element"><a class="wb_button" href="MPO50/"><span>Подробнее..</span></a></div><div id="wb_element_instance81" class="wb_element"><a class="wb_button" href="OVS/"><span>Подробнее..</span></a></div><div id="wb_element_instance82" class="wb_element"><a class="wb_button" href="ZVS/"><span>Подробнее..</span></a></div><div id="wb_element_instance83" class="wb_element"><a class="wb_button" href="VRM/"><span>Подробнее..</span></a></div><div id="wb_element_instance84" class="wb_element"><a class="wb_button" href="trier/"><span>Подробнее..</span></a></div><div id="wb_element_instance85" class="wb_element"><a class="wb_button" href="MZK-70/"><span>Подробнее..</span></a></div><div id="wb_element_instance86" class="wb_element"><a class="wb_button" href="ZSK-70/"><span>Подробнее..</span></a></div><div id="wb_element_instance87" class="wb_element" style="width: 100%;">
                <script type="text/javascript">
                    $(function() {
                        $("#wb_element_instance87").hide();
                    });
                </script>
            </div></div><div class="wb_cont_outer"></div><div class="wb_cont_bg"></div></div>

<?php get_footer()?>
